2023-08-27 13:22:01.186906 | Traceback (most recent call last):
  File "F:\Education\Alevel\alevel_hw\Lesson_17_hw\lesson_17_hw.py", line 15, in __init__
    self.validate_email(email)
  File "F:\Education\Alevel\alevel_hw\Lesson_17_hw\lesson_17_hw.py", line 33, in validate_email
    raise EmailAlreadyExistsException(f'Email {email} is already used!')
EmailAlreadyExistsException: Email asdf1@rinvs.dmvmds is already used!

